export const categories = [
  { id: 'engine', name: 'Двигатель', color: '#D32F2F', image: 'https://png.monster/wp-content/uploads/2022/09/png.monster-155.png', path: '/catalog/engine' },
  { id: 'transmission', name: 'Трансмиссия', color: '#455A64', image: 'https://static.tildacdn.com/tild3133-3136-4438-b131-626566633634/2-2.png', path: '/catalog/transmission' },
  { id: 'chassis', name: 'Подвеска', color: '#0288D1', image: 'https://pngimg.com/d/car_parts_PNG10141.png', path: '/catalog/chassis' },
  { id: 'brakes', name: 'Тормоза', color: '#FBC02D', image: 'https://www.freepnglogos.com/uploads/caliper-png/brake-caliper-png-transparent-images-21.png', path: '/catalog/brakes' },
  { id: 'electronics', name: 'Электроника', color: '#303F9F', image: 'https://pngimg.com/d/car_parts_PNG10145.png', path: '/catalog/electronics' },
  { id: 'cooling', name: 'Охлаждение', color: '#0097A7', image: 'https://avtopasker.ru/photo/big/223611.png', path: '/catalog/cooling' },
  { id: 'body', name: 'Кузов', color: '#616161', image: 'https://www.picng.com/upload/car_door/png_car_door_32903.png', path: '/catalog/body' },
  { id: 'safety', name: 'Безопасность', color: '#388E3C', image: 'https://static.tildacdn.com/tild3532-6131-4131-b664-323330663432/1.png', path: '/catalog/safety' },
  { id: 'filters', name: 'Фильтры', color: '#F5F5F5', image: 'https://www.freeiconspng.com/uploads/car-oil-filter-png-6.png', path: '/catalog/filters' },
  { id: 'liquids', name: 'Жидкости', color: '#512DA8', image: 'https://pngimg.com/d/jerrycan_PNG17.png', path: '/catalog/liquids' },
  { id: 'interior', name: 'Интерьер', color: '#795548', image: 'https://www.pngall.com/wp-content/uploads/2016/04/Steering-Wheel-PNG-Clipart.png', path: '/catalog/interior' },
  { id: 'accessories', name: 'Аксессуары', color: '#00796B', image: 'https://png.monster/wp-content/uploads/2022/09/png.monster-180.png', path: '/catalog/accessories' },
  { id: 'tires', name: 'Шины', color: '#212121', image: 'https://pngimg.com/d/tire_PNG11.png', path: '/catalog/tires' },
];